// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID           int64        `db:"id"`
	Uuid         string       `db:"uuid"`
	Email        string       `db:"email"`
	HashPassword string       `db:"hash_password"`
	CreatedAt    time.Time    `db:"created_at"`
	UpdatedAt    time.Time    `db:"updated_at"`
	DeletedAt    sql.NullTime `db:"deleted_at"`
}

type Session struct {
	ID           int64     `db:"id"`
	Uuid         string    `db:"uuid"`
	RefreshToken string    `db:"refresh_token"`
	UserAgent    string    `db:"user_agent"`
	ClientID     string    `db:"client_id"`
	IsBlocked    bool      `db:"is_blocked"`
	ExpiredAt    time.Time `db:"expired_at"`
	CreatedAt    time.Time `db:"created_at"`
}

type User struct {
	ID        int64          `db:"id"`
	Uuid      string         `db:"uuid"`
	FirstName sql.NullString `db:"first_name"`
	LastName  sql.NullString `db:"last_name"`
	Birthday  sql.NullTime   `db:"birthday"`
	Address   sql.NullString `db:"address"`
	Phone     sql.NullString `db:"phone"`
	CreatedAt time.Time      `db:"created_at"`
	UpdatedAt time.Time      `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}
